### ISSUE TITLE
Support Files.copy(InputStream, Path, ...)

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-utilities#10]
To be able to complete PR https://github.com/Terracotta-OSS/terracotta-platform/pull/686

**Comment by mathieucarbou** [comment]
FYI @saurabhagas @chrisdennis @cljohnso . Don't know if it is something worth having in the Files utility ?

**Comment by cljohnso** [comment]
Closed by #34
